name: recipes
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  http: ^1.1.0
  url_launcher: ^6.1.10

  cupertino_icons: ^1.0.8

  # STATE MANAGEMENT â€” OVA TI NEDOSTASUVA
  provider: ^6.0.5

  # FIREBASE & NOTIFICATIONS
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  firebase_messaging: ^16.0.4
  flutter_local_notifications: ^18.0.1

  shared_preferences: ^2.5.3
  timezone: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
